### ISSUE TITLE
Bug #3 - Checkbox «Select All» for links doesn't work at the next page

### ISSUE THREAD

**Issue by Leobios** [NEAR-labs/ui.near-linkdrop#23]
При переході на сторінку з наступними 50-ма лінками не працює чекбокс «Відмітити всі». Після повернення на початкову сторінку чекбокс також перестає працювати. Потрібно оновлення сторінки.
![image](https://user-images.githubusercontent.com/89875524/137110959-94ca7c93-dd19-47c2-ba09-5cb4378306cf.png)
![image](https://user-images.githubusercontent.com/89875524/137111103-bc1b9a59-a63c-4a46-b369-89d41e1edf87.png)
![image](https://user-images.githubusercontent.com/89875524/137111234-f4f73761-ddf5-4ed1-b4f6-ce69f0043658.png)

**Comment by eclipseeer** [comment]
Not relevant as far as we don't have checkboxes anymore
