### ISSUE TITLE
Bounty #1 - Implement UI Redesign of "Campaign Page"

### ISSUE THREAD

**Issue by eclipseeer** [NEAR-labs/ui.near-linkdrop#49]
# About the Bounty

This bounty is related to the application https://neardrop.io/, and has a very specific scope of implementing already finalized mockups into our open-source code-base. If you are interested in the bounty please comment on this thread and we will get you access to the design + doing pull requests.

# Acceptance criteria for Campaign page

- [x] Create a new modular, scalable architecture for a campaign component page - should be easy to add a new page for other campaign types in the future.
- [x] Rework campaign page layout according to the new designs:
  - [x] Rework pagination
  - [x] Add new ‘More’ button with tooltip
  - [x] Add ‘Show NFT’ button for NFT campaign type
  - [x] Add ‘Campaign Analytics’ which should lead to the new page, which will be added later
  - [x] Remove ‘Public Key’ field from UI and CSV file
  - [x] Rework drop status display - instead of showing 4 statuses (active, claimed, created, refunded) show only active/inactive.
  - [x] Add new styles for the tooltip (in the whole app)
  - [x] Add tooltips for every button in the row
  - [x] Rework mobile version
- [x] Add a new modal for QR code
- [x] Add preview window for NFT
- [x] Implement redirects - user should not be able to open this page when it is:
    - [x] Not active (in creation/deletion)
    - [x] Not user’s own campaign (without seed phrase can’t show drops)
- [x] Test the page and make sure that there are no bugs

# Acceptance criteria for Campaigns page
- [x] Rework page layout according to designs (links - it is a total amount of drops
- [x] Remove the ‘More’ button

# Bounty
$1,000 USD in NEAR using the USD/NEAR fx rate of the date of delivery

**Comment by Bonifface** [comment]
Hi, I would like to do this bounty. I can start immediately.

**Comment by Bonifface** [comment]
Hi, I've done with the task, please review it: https://dev-app-neardrop.netlify.app/campaigns
